name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: check code
        run: npx prettier ./src/ --check
      - name: send good message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: -4587543996
          token: ${{ secrets.token }}
          message: Код хороший
      - name: sand bad message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: -4587543996
          token: ${{ secrets.token }}
          message: Гавно написал

  build:
     runs-on: ubuntu-latest
     needs: [ lint ]
     steps:
      - uses: actions/checkout@v4

      - name: Buid docker image
        run: docker build -t ghcr.io/kryakva-krya-krya/practic-4/students-node-330:latest ./src/
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        run: docker push ghcr.io/kryakva-krya-krya/practic-4/students-node-330:latest
      - name: send good message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: -4587543996
          token: ${{ secrets.token }}
          message: Еще и запушился
      - name: sand bad message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: -4587543996
          token: ${{ secrets.token }}
          message: А, нет. Все-таки гавно
      - name: send message
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 92.246.136.16
          username: kryakva-krya-krya
          password: 55gteKGRQKG5
          port: ${{ secrets.PORT }}
          run: echo "test message from kryakva(nkolay)"
